repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.12.11"
    hooks:
      - id: ruff
        name: Ruff
        args: [ "--fix",
                "--show-fixes",
                "--select", "E,W,F,B,I,C4,EM,ICN,ISC,PGH,PIE,PL,PT,RET,RUF,SIM,UP,YTT,EXE,NPY,PD",
                "--ignore", "E501,PT004,RET505,RET506,RET507,RET508,SIM108,PLR2004",
                "--unsafe-fixes"
        ]
      - id: ruff-format
        name: Ruff Format
