apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.auth.aws_access_key_id }}
  password: {{ .Values.auth.aws_secret_access_key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-region
type: kubernetes.io/basic-auth
stringData:
  password: {{ .Values.auth.aws_region }}
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-coamps-credentials
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.auth.aws_coamps_access_key_id }}
  password: {{ .Values.auth.aws_coamps_secret_access_key }}
