{{ if .Values.config.storage.use_aws_ebs }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 20Gi
{{ else }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
{{ end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - image: {{ .Values.containers.database.image }}:{{ .Values.containers.version }}
        imagePullPolicy: Always
        name: database
        resources:
          requests:
            cpu: 1000m
            memory: 4Gi
            ephemeral-storage: 2Gi
          limits:
            memory: 5Gi
            ephemeral-storage: 4Gi
        livenessProbe:
          exec:
            command: [ "pg_isready" ]
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 3
          failureThreshold: 5
          successThreshold: 1
        readinessProbe:
          exec:
            command: [ "pg_isready" ]
          initialDelaySeconds: 15
          timeoutSeconds: 5
          periodSeconds: 3
          failureThreshold: 5
          successThreshold: 1
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: database.name
        - name: PGDATA
          value: /var/lib/postgresql/data/database-data
        ports:
        - containerPort: 5432
          name: db-port
        volumeMounts:
        - name: database-persistent-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: database-persistent-storage
        persistentVolumeClaim:
          claimName: database-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
  selector:
    app: database
---
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: {{ .Values.auth.database_root_password }}
