apiVersion: apps/v1
kind: Deployment
metadata:
  name: keymanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keymanager
  template:
    metadata:
      labels:
        app: keymanager
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - image: {{ .Values.containers.key_manager.image }}:{{ .Values.containers.version }}
        imagePullPolicy: Always
        name: keymanager
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 2Gi
        stdin: true
        stdinOnce: true
        tty: true
        env:
        - name: METGET_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: METGET_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: METGET_DATABASE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: database.name
        - name: METGET_REQUEST_TABLE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: database.request_table
        - name: METGET_API_KEY_TABLE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: database.apikey_table
