apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskQueue
  template:
    metadata:
      labels:
        app: taskQueue
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        resources:
          requests:
            cpu: 100m
            memory: 1Gi
            ephemeral-storage: 1Gi
          limits:
            cpu: 200m
            memory: 2Gi
            ephemeral-storage: 2Gi
        ports:
          - containerPort: 5672
          - containerPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq
spec:
  type: ClusterIP
  ports:
    - name: "5672"
      port: 5672
      targetPort: 5672
  selector:
    app: taskQueue
