apiVersion: apps/v1
kind: Deployment
metadata:
  name: rebuild
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rebuild
  template:
    metadata:
      labels:
        app: rebuild
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - image: {{ .Values.containers.rebuild.image }}:{{ .Values.containers.version }}
        imagePullPolicy: Always
        name: rebuild
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 2Gi
        stdin: true
        stdinOnce: true
        tty: true
        env:
        - name: METGET_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: username
        - name: METGET_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: password
        - name: METGET_DATABASE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: database.name
        - name: METGET_REQUEST_TABLE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: database.request_table
        - name: METGET_API_KEY_TABLE
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: database.apikey_table
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: username
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: password
        - name: AWS_DEFAULT_REGION
          valueFrom:
            secretKeyRef:
              name: aws-region
              key: password
        - name: METGET_S3_BUCKET
          valueFrom:
            configMapKeyRef:
              name: configmap
              key: s3.storage_bucket
        - name: COAMPS_S3_BUCKET
          value: {{ .Values.s3.coamps_storage_bucket }}
        - name: COAMPS_AWS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-coamps-credentials
              key: username
        - name: COAMPS_AWS_SECRET
          valueFrom:
            secretKeyRef:
              name: aws-coamps-credentials
              key: password
