apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Release.Name }}-rebuild
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: {{ .Release.Name }}-rebuild
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-rebuild
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - image: {{ .Values.containers.rebuild.image }}:{{ .Values.containers.version }}
        imagePullPolicy: Always
        name: {{ .Release.Name }}-rebuild
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 2Gi
        stdin: true
        stdinOnce: true
        tty: true
        env:
        - name: METGET_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-database-secret
              key: username  
        - name: METGET_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-database-secret
              key: password
        - name: METGET_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: database.name
        - name: METGET_REQUEST_TABLE
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: database.request_table
        - name: METGET_API_KEY_TABLE
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: database.apikey_table
