# Reusable workflow for building the containers
name: Build Containers Workflow Template
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
      push:
        required: true
        type: boolean
    secrets:
      DOCKERHUB_LOGIN_USERNAME:
        required: true
      DOCKERHUB_LOGIN_TOKEN:
        required: true

jobs:
  build-metget-api:
    name: Build metget-server api container
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push metget-api Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./containers/api/Dockerfile
          push: ${{ inputs.push }}
          platforms: linux/amd64,linux/arm64
          tags: thewaterinstitute/metget-api:${{ inputs.tag }}
          labels: org.metget.metget-server
          provenance: mode=max
          sbom: true

  build-metget-database:
    name: Build metget-server database container
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push metget-database Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./containers/database/Dockerfile
          push: ${{ inputs.push }}
          platforms: linux/amd64,linux/arm64
          tags: thewaterinstitute/metget-database:${{ inputs.tag }}
          labels: org.metget.metget-server
          provenance: mode=max
          sbom: true

  build-metget-download:
    name: Build metget-server download container
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push metget-download Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./containers/download/Dockerfile
          push: ${{ inputs.push }}
          platforms: linux/amd64,linux/arm64
          tags: thewaterinstitute/metget-download:${{ inputs.tag }}
          labels: org.metget.metget-server
          provenance: mode=max
          sbom: true

  build-metget-rebuild:
    name: Build metget-server rebuild container
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push metget-rebuild Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./containers/rebuild/Dockerfile
          push: ${{ inputs.push }}
          platforms: linux/amd64,linux/arm64
          tags: thewaterinstitute/metget-rebuild:${{ inputs.tag }}
          labels: org.metget.metget-server
          provenance: mode=max
          sbom: true

  build-metget-keymanager:
    name: Build metget-server keymanager container
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push metget-keymanager Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./containers/keymanager/Dockerfile
          push: ${{ inputs.push }}
          platforms: linux/amd64,linux/arm64
          tags: thewaterinstitute/metget-keymanager:${{ inputs.tag }}
          labels: org.metget.metget-server
          provenance: mode=max
          sbom: true

  build-metget-build:
    name: Build metget-server build container
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and push metget-build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./containers/build/Dockerfile
          push: ${{ inputs.push }}
          platforms: linux/amd64,linux/arm64
          tags: thewaterinstitute/metget-build:${{ inputs.tag }}
          labels: org.metget.metget-server
          provenance: mode=max
          sbom: true
