# Reusable workflow for building the containers
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      DOCKERHUB_LOGIN_USERNAME:
        required: true
      DOCKERHUB_LOGIN_TOKEN:
        required: true

jobs:
  build:
    name: Build metget-server containers
    runs-on: ubuntu-latest
    steps:
      - name: Checkout metget-server
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_LOGIN_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN_USERNAME }} --password-stdin

      - name: Build and push metget-api Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./containers/api/Dockerfile
          push: true
          tags: thewaterinstitute/metget-api:${{ inputs.tag }}
          labels: metget-server

      - name: Build and push metget-database Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./containers/database/Dockerfile
          push: true
          tags: thewaterinstitute/metget-database:${{ inputs.tag }}
          labels: metget-server