# Reusable workflow for building the containers
name: Build Containers Workflow Template
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      DOCKERHUB_LOGIN_USERNAME:
        required: true
      DOCKERHUB_LOGIN_TOKEN:
        required: true

jobs:
  build-metget-api:
    name: Build metget-server api container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout metget-server
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_LOGIN_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN_USERNAME }} --password-stdin

      - name: Build and push metget-api Docker image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          file: ./containers/api/Dockerfile
          push: true
#         platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          tags: thewaterinstitute/metget-api:${{ inputs.tag }}
          labels: org.metget.metget-server
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-metget-database:
    name: Build metget-server database container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout metget-server
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_LOGIN_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN_USERNAME }} --password-stdin

      - name: Build and push metget-database Docker image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          file: ./containers/database/Dockerfile
          push: true
#         platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          tags: thewaterinstitute/metget-database:${{ inputs.tag }}
          labels: org.metget.metget-server
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-metget-download:
    name: Build metget-server download container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout metget-server
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_LOGIN_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN_USERNAME }} --password-stdin

      - name: Build and push metget-download Docker image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          file: ./containers/download/Dockerfile
          push: true
#         platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          tags: thewaterinstitute/metget-download:${{ inputs.tag }}
          labels: org.metget.metget-server
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-metget-rebuild:
    name: Build metget-server rebuild container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout metget-server
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_LOGIN_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN_USERNAME }} --password-stdin

      - name: Build and push metget-rebuild Docker image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          file: ./containers/rebuild/Dockerfile
          push: true
          #         platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          tags: thewaterinstitute/metget-rebuild:${{ inputs.tag }}
          labels: org.metget.metget-server
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-metget-keymanager:
    name: Build metget-server keymanager container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout metget-server
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_LOGIN_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN_USERNAME }} --password-stdin

      - name: Build and push metget-keymanager Docker image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          file: ./containers/keymanager/Dockerfile
          push: true
#         platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          tags: thewaterinstitute/metget-keymanager:${{ inputs.tag }}
          labels: org.metget.metget-server
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-metget-build:
    name: Build metget-server build container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout metget-server
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKERHUB_LOGIN_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN_USERNAME }} --password-stdin

      - name: Build and push metget-build Docker image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
        with:
          context: .
          file: ./containers/build/Dockerfile
          push: true
#         platforms: linux/amd64,linux/arm64
          platforms: linux/amd64
          tags: thewaterinstitute/metget-build:${{ inputs.tag }}
          labels: org.metget.metget-server
          cache-from: type=gha
          cache-to: type=gha,mode=max
