#...Github Actions workflow to run a release build of the containers
#...and push them to Docker Hub as stable-<release_version>
name: Release Containers Build
on:
  release:
    types: [published]
jobs:
  get_release_version:
    name: Get Release Version
    runs-on: ubuntu-latest
    outputs:
      RELEASE_VERSION: ${{ steps.vars.outputs.RELEASE_OUTPUT }}
    steps:
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $RELEASE_OUTPUT
  stable-version-build-and-deploy:
    uses: ./.github/workflows/build_containers.yml
    with:
      tag: ${{ needs.get_environment.outputs.RELEASE_VERSION }}-stable
    secrets: inherit
    needs: [get_release_version]