#...Github Actions workflow to run a PR build of the containers
name: PR Containers Build
on:
  pull_request:
      types: [opened, synchronize]

jobs:
  development-build-and-deploy:
    uses: ./.github/workflows/build_containers.yml
    with:
      tag: pr-${{ github.event.number }}
      push: false
    secrets: inherit
