name: Container build template
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      tag:
        required: true
        type: string
      push:
        required: true
        type: boolean
      dockerfile:
        required: true
        type: string
      organization:
        required: true
        type: string
      container_name:
        required: true
        type: string
      platform:
        required: true
        type: string
      runs_on:
        required: true
        type: string
    secrets:
      DOCKERHUB_LOGIN_USERNAME:
        required: true
      DOCKERHUB_LOGIN_TOKEN:
        required: true

jobs:
  build_container:
    name: Build ${{ inputs.name }}:${{ inputs.platform }}
    runs-on: ${{ inputs.runs_on }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare Platform
        run: |
          platform=${{ inputs.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build ${{ inputs.container_name }} Docker image
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          platforms: ${{ inputs.platform }}
          provenance: mode=max
          sbom: true
          outputs: type=image,name=${{ inputs.organization }}/${{ inputs.container_name }},push-by-digest=true,name-canonical=true,push=${{ inputs.push }}

      - name: Export digest
        run: |
          mkdir -p /tmp/${{ inputs.container_name }}/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/${{ inputs.container_name }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ inputs.container_name }}-${{ env.PLATFORM_PAIR }}
          path: /tmp/${{ inputs.container_name }}/digests/*
          if-no-files-found: error
          retention-days: 1
