#...Github Actions workflow to run a release build of the containers
#...and push them to Docker Hub as stable-<release_version>
name: Release Containers Build
on:
  release:
    types: [published]
jobs:
  stable-version-build-and-deploy:
    uses: ./.github/workflows/build_containers.yml
    with:
      tag: ${{ github.event.release.tag_name }}-stable
    secrets: inherit
