name: Container build template
on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      tag:
        required: true
        type: string
      dockerfile:
        required: true
        type: string
      organization:
        required: true
        type: string
      container_name:
        required: true
        type: string
    secrets:
      DOCKERHUB_LOGIN_USERNAME:
        required: true
      DOCKERHUB_LOGIN_TOKEN:
        required: true

jobs:
  build_push_amd64:
    name: Build ${{ inputs.name }}:amd64
    uses: ./.github/workflows/container_builder.yaml
    with:
      name: ${{ inputs.name }}
      tag: ${{ inputs.tag }}
      push: true
      dockerfile: ${{ inputs.dockerfile }}
      organization: ${{ inputs.organization }}
      container_name: ${{ inputs.container_name }}
      platform: linux/amd64
      runs_on: ubuntu-latest
    secrets: inherit

  build_push_arm64:
    name: Build ${{ inputs.name }}:arm64
    uses: ./.github/workflows/container_builder.yaml
    with:
      name: ${{ inputs.name }}
      tag: ${{ inputs.tag }}
      push: true
      dockerfile: ${{ inputs.dockerfile }}
      organization: ${{ inputs.organization }}
      container_name: ${{ inputs.container_name }}
      platform: linux/arm64
      runs_on: ubuntu24.04-ARM64
    secrets: inherit

  merge_containers:
    name: Merge ${{ inputs.name }}
    runs-on: ubuntu-latest
    needs:
      - build_push_amd64
      - build_push_arm64
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/${{ inputs.container_name }}/digests
          pattern: digests-${{ inputs.container_name }}-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN_USERNAME }}
          password: ${{ secrets.DOCKERHUB_LOGIN_TOKEN }}

      - name: Create manifest list and push
        working-directory: /tmp/${{ inputs.container_name }}/digests
        run: |
          docker buildx imagetools create --tag ${{ inputs.organization }}/${{ inputs.container_name }}:${{ inputs.tag }} \
          $(printf '${{ inputs.organization }}/${{ inputs.container_name }}@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ inputs.organization }}/${{ inputs.container_name }}:${{ inputs.tag }}
