#...Github Actions workflow to run a nightly build of the containers
#...and push them to Docker Hub
name: Stable Containers Build
on:
  push:
    branches:
      - main

jobs:
  development-build-and-deploy:
    uses: ./.github/workflows/build_containers.yml
    with:
      tag: stable
      push: true
    secrets: inherit
