name: Pull Request
on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build_pull_request:
    name: Build Containers
    uses: ./.github/workflows/all_containers_build_only.yaml
    with:
      tag: pr-${{ github.event.number }}
    secrets: inherit
  pre_commit:
    name: Pre-commit checks
    uses: ./.github/workflows/precommit.yaml
