name: Stable Deployment
on:
  push:
    branches:
      - main

jobs:
  build_pull_request:
    name: Build Containers
    uses: ./.github/workflows/all_containers_build_push.yaml
    with:
      tag: stable
    secrets: inherit
  pre_commit:
    name: Pre-commit checks
    uses: ./.github/workflows/precommit.yaml
